# Site settings
title: Deploying PHP Applications
email: niklas@modess.io

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://www.deployingphpapplications.com" # the base hostname & protocol for your site

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: envelope
    url: mailto:niklas@modess.io
  - title: twitter
    url: https://twitter.com/niklasmodess

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Build settings
